version: "3.9"

networks:
  devops-net:
    driver: bridge

volumes:
  db_data:
  grafana_data:

services:
  api:
    image: vinicius994/devops-docker-api:latest
    container_name: devops-docker-api-2
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devopsdb
      - SPRING_DATASOURCE_USERNAME=devops
      - SPRING_DATASOURCE_PASSWORD=devops123
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - db
    networks:
      - devops-net
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: devops-db
    environment:
      - POSTGRES_DB=devopsdb
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=devops123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devops-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: devops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - devops-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: devops-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - devops-net
    depends_on:
      - prometheus
    restart: unless-stopped
